sudo: required
dist: trusty
language: node_js
node_js:
- '8'
script:
# - npm run lint
# - npm run test
- npm run build
cache:
  yarn: false 
  directories:
  - node_modules

env:
  global:
  - KEY_ONE=${REACT_APP_ENV}
  - KEY_TWO=$(echo "RAINT";)

before_install: echo ${REACT_APP_ENV}


deploy:
  ####   DEPLOYMENT    ####
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET
    bucket: idle-clicker
    region: us-west-2
    local_dir: build
    skip_cleanup: true
    on:
      all_branches: true
      # branch: travis 
