sudo: required
dist: trusty
language: node_js
node_js:
- '8'
script:
# - npm run lint
# - npm run test
- npm run build
cache:
  yarn: false 
  directories:
  - node_modules

deploy:
  ####   DEPLOYMENT    ####
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET
    bucket: idle-clicker
    local_dir: build
    skip_cleanup: true
    env:
      - KEY_ONE=one
      - KEY_TWO=two
    on:
      all_branches: true
      # branch: travis 
